### PR TITLE
Version History

### PR DESCRIPTION
**Pull request by GameMaker**
Added version history, with restore / delete.

Adds a new "History" button to blogControls template.
Every 'save' pushes a version to the history array.

### CODE REVIEW

**Comment by samhatoum** [comment]
Thanks Aaron, could you please [squash](http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git/5201642#5201642) this?

You can do this locally then overwrite the current pushes here.

Also, the package.js file should refer to xolvio:md-blog

Thanks :)

**Comment by GameMaker** [comment]
Ok - finally figured out how to do a destructive squash (turns out I had already pushed, and the develop branch was still pointing to the commits).

Also removed references to the gamemaker:md-blog package.

I think that's what you're looking for, correct?

**Comment by samhatoum** [comment]
Thanks a lot for this Aaron. I just tested it and have found some issues that need some love!

* [ ] When updating the blog from my current version to the history one, clicking history on my old blog posts (don't have a history object yet) causes exceptions
* [ ] Changing fields on a blog post that didn't have a history object (as to create one) then navigating to an older one that still doesn't have a history object, then clicking history shows the history of the other blog post (session?)
* [ ] Changing a post title and clicking save created duplicate content

Some easy minor usability issues:
* [ ] Clicking history again should close the popup
* [ ] Popup needs a close button also
* [ ] History button should stay close to the other buttons since it's relevant to the pots (just remoe float right)

I know you were having some issues with the duplicate content bug and I'd be more than happy to jump in and fix if you still need me to after resolving the issues above.

I really appreciate this PR, it's going to be awesome when it gets in :)

**Comment by GameMaker** [comment]
Ok - next attempt is online. I believe I fixed all of those issues EXCEPT the duplicate content one - that's the one we discussed over the winter break, and I'm not sure what's causing it. If you could help figure that one out, it would be very helpful.

**Comment by samhatoum** [comment]
sure. where is it online? on the GameMaker repo?

**Comment by GameMaker** [comment]
Unless I've goofed, it's in this PR - I committed fixes to your items (except the duplication), and squashed the commit. If you do a pull, you should see the fixes - did I mess it up?

**Comment by samhatoum** [comment]
I really haven't forgotten this, it's a little behind commit wise. I'll be sure to get it all in when I have a half-day spare!

**Comment by GameMaker** [comment]
I noticed that - do you want me to rebase on the latest and resubmit?

**Comment by samhatoum** [comment]
Please. Would save me some work.

Also, there's a way you can work than having to release your own version of the md-blog to atmosphere.

Create a `/packages` directory in your project and clone your fork in there. Now you can use `xolvio:md-blog` and it will pick up your fork. This works because the `package.js` file contains `xolvio:md-blog` and Meteor is smart to figure that you're overriding with a local package.

**Comment by samhatoum** [comment]
actually, let me merge the latest from Olivier first

**Comment by samhatoum** [comment]
The other branch is merged

**Comment by GameMaker** [comment]
Hi Sam - I've merged the latest from your master, and added placeholder French localization text (I'm working on getting french text for the history system, will send it later). Please try again. If this doesn't work, I will need to start a new PR so you can get it in one commit. git rebase is not letting me squash commits over the merge commit - it doesn't even show up in the history. I'd really like this PR to be resolved. It's been quite the learning experience.

**Comment by samhatoum** [comment]
I'm checking this out locally and running through the code, making any changes as I need to (to cut the feedback cycle).

I'll try to get this out late this evening.

**Comment by GameMaker** [comment]
Sounds good. Hopefully the only issue is the occasional duplication of content. It's cosmetic but intermittent and annoying. I think it might be due to reactivity and Router.go-ing, perhaps after upsert. 

The only othe alternative I can think of is making a new pull request from a clean feature branch. I can do that if you'd prefer but if you're making progress I vote keep going. 

Thanks,
Aaron

**Comment by samhatoum** [comment]
Hey @GameMaker 

I just tested this locally and there are still a few bugs (using the standard app)

* [ ] Clicking history on the blog post list opens all history tabs for all posts
* [ ] When restoring a version and the restored version is re-inserted at the top of the history list, the history list is not updated reactively (on page refresh it becomes visible)
* [ ] There are some server errors like `Exception while invoking method 'mdblog-getHistory' TypeError: Cannot call method 'push' of undefined
`

I know we went through quite a few experimentation and iterations to get to this point and therefore the code has become a little organic, so what I'd like to do with this feature is close this PR and I will re-write it soon, using a) testing and b) all the lessons learnt from our experiments!

Sorry to have to do this, I genuinely appreciate your hard work. It's just going to take me more time to get through the issues than it would take me to rewrite it and I'm worried about future changes being fragile without the testing in place too, given that there's a lot of code here.

**Comment by GameMaker** [comment]
That makes perfect sense. Good idea on reorganizing around bug issues. Thanks!

**Pull request closed without merging**
