### PR TITLE
Add support for blog path customization

### PR DESCRIPTION
**Pull request by adeubank**
*Summary*

* Changes the way md-blog parses it's settings to be a little more succinct with underscore js's "default" method.
* Extend the default settings for the blog by adding options to customize the url path that handles the blog.
* Also supports running the blog at the root url, "/".

### CODE REVIEW

**Comment by adeubank** [comment]
Love what you're doing here, xolvio, I am running a customized version of it at https://alleneubank.com. Looking forward to collaborating with you.

**Comment by samhatoum** [comment]
This awesome, thank you so much! I'm hoping to get this PR and the History one both later today (PST time).

**Comment by samhatoum** [comment]
I've had a chance to look at this and test it. Impressive work, thank you VERY much!

Would you mind also updating the docs to let people know what the options do?

**Comment by samhatoum** [comment]
And the defaults is sooo much better than the crap I had!

**Comment by adeubank** [comment]
Thanks for the feedback, Xolvio! Let me know what you think. I updated the default settings.json file and added a **Blog Routes** section to the README.

**Comment by samhatoum** [comment]
Perfect! Thank you so very much sir

**Comment by samhatoum** [comment]
released v0.3.7. Thanks again

**Pull request merged**
