### PR TITLE
I18n fixes

### PR DESCRIPTION
**Pull request by ogourment**
- Various minor fixes for i18n
- Upgrade to Meteor 1.0.4.2

### CODE REVIEW

**Comment by samhatoum** [comment]
amazing! Do you want to publish this new package or shall I?

**Comment by ogourment** [comment]
I'll run a quick sanity check in md-blog.meteor.com and publish.

**Comment by samhatoum** [comment]
:+1:

**Comment by samhatoum** [comment]
thank you for your work, I'll use this in the testing manual soon!

**Comment by ogourment** [comment]
Published xolvio:md-blog@0.5.0.

**Pull request merged**
